aspire_acceptance_column_headers = [
    "TESTCASE",
    "EQUITY",
    "TOTAL_CASH_PRICE",
    "DOWN_PAYMENT",
    "TITLE_PREP_FEE",
    "REG_FEE",
    "DOC_FEE",
    "REQUESTED_TERM",
    "FHF_WARRANTY_CHECK",
    "FHF_GAP_CHECK",
    "WARRANTY",
    "GAP_INSURANCE",
    "HARD_ADD_ONS",
    "OTHER_PRODUCT_PRICE",
    "MAINTENANCE_FEE",
    "FREIGHT_FEE",
    "STAMP_TAX",
    "TIRE_AND_WHEEL_FEE",
    "SALES_TAX",
    "VSI",
    "AF",
    "VEHICLE_VALUE",
    "LTV_3_LSL",
    "AVG_TRADEIN_VALUE",
    "LUXURY",
    "MAKE",
    "MILEAGE",
    "MODEL",
    "REGION",
    "VALUE_SOURCE",
    "VEHICLE_CONDITION",
    "VEHICLE_YEAR",
    "VIN",
    "SSN",
    "ZIP_CODE",
    "LOAN_PROGRAM_ID",
]

aspire_acceptance_input = {
    "TOTAL_CASH_PRICE": [10000, 50000],
    "TITLE_PREP_FEE": "200",
    "REG_FEE": "100",
    "DOC_FEE": "150",
    "REQUESTED_TERM": "72",
    "FHF_WARRANTY_CHECK": "0",
    "FHF_GAP_CHECK": "0",
    "WARRANTY": "500",
    "GAP_INSURANCE": "100",
    "HARD_ADD_ONS": "600",
    "OTHER_PRODUCT_PRICE": "200",
    "MAINTENANCE_FEE": "200",
    "FREIGHT_FEE": "0",
    "STAMP_TAX": "0",
    "TIRE_AND_WHEEL_FEE": "700",
    "VSI": "200",
    "LUXURY": "0",
    "MAKE": "ACURA, HONDA, JEEP",
    "MILEAGE": "10",
    "MODEL": "CR-V, Odyssey",
    "REGION": "EASTERN",
    "VALUE_SOURCE": "Manual Other",
    "VEHICLE_CONDITION": "New, Used",
    "VEHICLE_YEAR": "2025",
    "VIN": "19ude4h37ra013135, 5J6RE487X9L059421, 5FNRL6H75LB073406",
    "SSN": "666140220, 666010068, 666670630",
    "ZIP_CODE": "70001, 70002, 70000",
    "LOAN_PROGRAM_ID": "008_039",
}
